### ISSUE TITLE
Not generating correct no of words

### ISSUE THREAD

**Issue by Sayan4444** [pydeep9026/random-text-generator#1]
If we select the word count, it does not follow that that, it generates the number of words of its choice

**Comment by pydeep9026** [comment]
Hey brother it's working maybe post a screenshot if possible in my devices it's working fine

**Comment by Sayan4444** [comment]
No of words given is 50 but the words showed is not 50

**Comment by pydeep9026** [comment]
Okk that's because Json dataset I am using doesn't have sentences with 50 words
I will reduce the limit for that thnks

**Comment by pydeep9026** [comment]
check it out i have solved the issue and added a toast when you use a wordcount >20  so now it should work well

**Comment by Sayan4444** [comment]
Hello brother....there are still issues....if the word count is 20 its
printing 23 words....moreover why wont someone be able to print more that
20 words..... can I contribute to ur project?

**Comment by pydeep9026** [comment]
Bro the reason being I was given data.json file and cannot use another file or dataset. Maybe I will merge arrays from dataset.

**Comment by pydeep9026** [comment]
hey brother ,
i corrected the wordcount issue now it will give you 20 words only on wordcount of 20.
and also i increased the word count limit to 100

**Comment by Sayan4444** [comment]
Great brother

**Comment by Sayan4444** [comment]
Can I ask are u in github octernship?

**Comment by pydeep9026** [comment]
no i am not. are you?

**Comment by Sayan4444** [comment]
Yes I am and that's how I found u bro

**Comment by pydeep9026** [comment]
good for you bro, how do i get one btw?

**Comment by Sayan4444** [comment]
Are u in clg?

**Comment by pydeep9026** [comment]
Yes 4th sem btech cse

**Comment by Sayan4444** [comment]
Then u can apply for github octernship
